### ISSUE TITLE
Opening a remote file is blank

### ISSUE THREAD

**Issue by SimCoxuK** [mgrenier/remote-ftp#2]
When opening a remote file from the FTP it shows the contents of this file to be completely blank, to view the contents of this file, I need to view it in local view and then edit from there, would be great if we could open the downloaded local file when trying to open a file from the server.

**Comment by lenguyenitc** [comment]
Hello mgrenier, This is really great package. Have you solve this problem. I'm using the latest version of package but still same issue?

**Comment by Sabe67** [comment]
Same problem on Windows 10 !

**Comment by oscarhogervorst** [comment]
Old issue, but it can still occur. And I found a fix. It turns out that if you use the "remote" setting in your config file it's important to both start and end with a  "/" character. In my case not doing this resulted in local creating a folder named "l" that did not match the remote structure.
Using this value worked
`"remote": "/public_html/",`
